export const GET_MEETING_REQUEST = 'GET_MEETING_REQUEST'
export const GET_MEETING_SUCCESS = 'GET_MEETING_SUCCESS'
export const GET_MEETING_FAIL = 'GET_MEETING_FAIL'

export const CREATE_MEETING_REQUEST = 'CREATE_MEETING_REQUEST'
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
export const CREATE_MEETING_FAIL = 'CREATE_MEETING_FAIL'


